version: '3.3'
services:
  redis:
    image: redis
    ports:
      - '6973:6973'
    volumes:
      - '/c/Users/lawre/Dev/redis-test:/app'
  redisinsight:
    image: redislabs/redisinsight
    volumes:
      - '/c/temp/redis-test:/db'
    ports:
      - '8001:8001'
  ngninx:
    image: openresty/openresty
    volumes: 
      - '/c/temp/online-celebration/nginx/:/etc/nginx/conf.d/'
    ports:
      - '80:80'
